openapi: 3.0.0
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
tags:
- name: pet
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  "/pet":
    $ref: "./modules/pet/api.yaml#/~1pet"  
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
components:
  schemas:
    $ref: "./components/schemas.yaml"
  securitySchemes:
    $ref: "./components/securitySchemes.yaml"
